//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(Subscription.CLASS_NAME, typeof(Subscription))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type Subscription.
	/// </summary>
	public partial class Subscription : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.Subscription";


		/// <summary>
		/// The instance of the class that provides extended API for working with Subscription fields.
		/// </summary>
		private readonly SubscriptionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with Subscription fields.
		/// </summary>
		[RegisterProperty]
		public SubscriptionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Subscription fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SubscriptionFields : AbstractHierarchicalObject<SubscriptionFields>
		{
			/// <summary>
			/// The content item of type Subscription that is a target of the extended API.
			/// </summary>
			private readonly Subscription mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SubscriptionFields" /> class with the specified content item of type Subscription.
			/// </summary>
			/// <param name="instance">The content item of type Subscription that is a target of the extended API.</param>
			public SubscriptionFields(Subscription instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Subscription" /> class.
		/// </summary>
		public Subscription() : base(CLASS_NAME)
		{
			mFields = new SubscriptionFields(this);
		}

		#endregion
	}
}