//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(CoffeeSection.CLASS_NAME, typeof(CoffeeSection))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type CoffeeSection.
	/// </summary>
	public partial class CoffeeSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.CoffeeSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with CoffeeSection fields.
		/// </summary>
		private readonly CoffeeSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with CoffeeSection fields.
		/// </summary>
		[RegisterProperty]
		public CoffeeSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CoffeeSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CoffeeSectionFields : AbstractHierarchicalObject<CoffeeSectionFields>
		{
			/// <summary>
			/// The content item of type CoffeeSection that is a target of the extended API.
			/// </summary>
			private readonly CoffeeSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CoffeeSectionFields" /> class with the specified content item of type CoffeeSection.
			/// </summary>
			/// <param name="instance">The content item of type CoffeeSection that is a target of the extended API.</param>
			public CoffeeSectionFields(CoffeeSection instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CoffeeSection" /> class.
		/// </summary>
		public CoffeeSection() : base(CLASS_NAME)
		{
			mFields = new CoffeeSectionFields(this);
		}

		#endregion
	}
}