//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace DancingGoat.Models
{
	/// <summary>
	/// Represents a content item of type <see cref="Coffee"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Coffee : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "DancingGoat.Coffee";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


        /// <summary>
        /// Name.
        /// </summary>
        public string Name { get; set; }


        /// <summary>
        /// CoffeeShortDescription.
        /// </summary>
        public string CoffeeShortDescription { get; set; }


        /// <summary>
        /// Description.
        /// </summary>
        public string Description { get; set; }


        /// <summary>
        /// Image.
        /// </summary>
        public IEnumerable<Image> Image { get; set; }


        /// <summary>
        /// CoffeeProcessing.
        /// </summary>
        public IEnumerable<TagReference> CoffeeProcessing { get; set; }


        /// <summary>
        /// CoffeeTastes.
        /// </summary>
        public IEnumerable<TagReference> CoffeeTastes { get; set; }
    }
}