//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(HomeSection.CLASS_NAME, typeof(HomeSection))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type HomeSection.
	/// </summary>
	public partial class HomeSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.HomeSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with HomeSection fields.
		/// </summary>
		private readonly HomeSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HomeSectionID.
		/// </summary>
		[DatabaseIDField]
		public int HomeSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HomeSectionID"), 0);
			}
			set
			{
				SetValue("HomeSectionID", value);
			}
		}


		/// <summary>
		/// HomeSectionText.
		/// </summary>
		[DatabaseField]
		public string HomeSectionText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeSectionText"), @"");
			}
			set
			{
				SetValue("HomeSectionText", value);
			}
		}


		/// <summary>
		/// HomeSectionLinkText.
		/// </summary>
		[DatabaseField]
		public string HomeSectionLinkText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeSectionLinkText"), @"");
			}
			set
			{
				SetValue("HomeSectionLinkText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with HomeSection fields.
		/// </summary>
		[RegisterProperty]
		public HomeSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with HomeSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HomeSectionFields : AbstractHierarchicalObject<HomeSectionFields>
		{
			/// <summary>
			/// The content item of type HomeSection that is a target of the extended API.
			/// </summary>
			private readonly HomeSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HomeSectionFields" /> class with the specified content item of type HomeSection.
			/// </summary>
			/// <param name="instance">The content item of type HomeSection that is a target of the extended API.</param>
			public HomeSectionFields(HomeSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HomeSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HomeSectionID;
				}
				set
				{
					mInstance.HomeSectionID = value;
				}
			}


			/// <summary>
			/// HomeSectionText.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.HomeSectionText;
				}
				set
				{
					mInstance.HomeSectionText = value;
				}
			}


			/// <summary>
			/// HomeSectionLinkText.
			/// </summary>
			public string LinkText
			{
				get
				{
					return mInstance.HomeSectionLinkText;
				}
				set
				{
					mInstance.HomeSectionLinkText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="HomeSection" /> class.
		/// </summary>
		public HomeSection() : base(CLASS_NAME)
		{
			mFields = new HomeSectionFields(this);
		}

		#endregion
	}
}