//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(Media.CLASS_NAME, typeof(Media))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type Media.
	/// </summary>
	public partial class Media : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.Media";


		/// <summary>
		/// The instance of the class that provides extended API for working with Media fields.
		/// </summary>
		private readonly MediaFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// MediaID.
		/// </summary>
		[DatabaseIDField]
		public int MediaID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("MediaID"), 0);
			}
			set
			{
				SetValue("MediaID", value);
			}
		}


		/// <summary>
		/// MediaFile.
		/// </summary>
		[DatabaseField]
		public string MediaFile
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MediaFile"), "");
			}
			set
			{
				SetValue("MediaFile", value);
			}
		}


		/// <summary>
		/// MediaShortDescription.
		/// </summary>
		[DatabaseField]
		public string MediaShortDescription
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MediaShortDescription"), @"");
			}
			set
			{
				SetValue("MediaShortDescription", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Media fields.
		/// </summary>
		[RegisterProperty]
		public MediaFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Media fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class MediaFields : AbstractHierarchicalObject<MediaFields>
		{
			/// <summary>
			/// The content item of type Media that is a target of the extended API.
			/// </summary>
			private readonly Media mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="MediaFields" /> class with the specified content item of type Media.
			/// </summary>
			/// <param name="instance">The content item of type Media that is a target of the extended API.</param>
			public MediaFields(Media instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// MediaID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.MediaID;
				}
				set
				{
					mInstance.MediaID = value;
				}
			}


			/// <summary>
			/// MediaFile.
			/// </summary>
			public global::CMS.DocumentEngine.ContentItemAsset File
			{
				get
				{
					return global::CMS.DocumentEngine.Internal.ContentItemAssetJsonConverter.ConvertToModel(mInstance, nameof(mInstance.MediaFile));
				}
			}


			/// <summary>
			/// MediaShortDescription.
			/// </summary>
			public string ShortDescription
			{
				get
				{
					return mInstance.MediaShortDescription;
				}
				set
				{
					mInstance.MediaShortDescription = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Media" /> class.
		/// </summary>
		public Media() : base(CLASS_NAME)
		{
			mFields = new MediaFields(this);
		}

		#endregion
	}
}