//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(ArticleSection.CLASS_NAME, typeof(ArticleSection))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type ArticleSection.
	/// </summary>
	public partial class ArticleSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.ArticleSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with ArticleSection fields.
		/// </summary>
		private readonly ArticleSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with ArticleSection fields.
		/// </summary>
		[RegisterProperty]
		public ArticleSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ArticleSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ArticleSectionFields : AbstractHierarchicalObject<ArticleSectionFields>
		{
			/// <summary>
			/// The content item of type ArticleSection that is a target of the extended API.
			/// </summary>
			private readonly ArticleSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ArticleSectionFields" /> class with the specified content item of type ArticleSection.
			/// </summary>
			/// <param name="instance">The content item of type ArticleSection that is a target of the extended API.</param>
			public ArticleSectionFields(ArticleSection instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ArticleSection" /> class.
		/// </summary>
		public ArticleSection() : base(CLASS_NAME)
		{
			mFields = new ArticleSectionFields(this);
		}

		#endregion
	}
}