//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.DancingGoatCore;

[assembly: RegisterDocumentType(Event.CLASS_NAME, typeof(Event))]

namespace CMS.DocumentEngine.Types.DancingGoatCore
{
	/// <summary>
	/// Represents a content item of type Event.
	/// </summary>
	public partial class Event : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DancingGoatCore.Event";


		/// <summary>
		/// The instance of the class that provides extended API for working with Event fields.
		/// </summary>
		private readonly EventFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// EventID.
		/// </summary>
		[DatabaseIDField]
		public int EventID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("EventID"), 0);
			}
			set
			{
				SetValue("EventID", value);
			}
		}


		/// <summary>
		/// EventPromoText.
		/// </summary>
		[DatabaseField]
		public string EventPromoText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("EventPromoText"), @"");
			}
			set
			{
				SetValue("EventPromoText", value);
			}
		}


		/// <summary>
		/// EventDate.
		/// </summary>
		[DatabaseField]
		public DateTime EventDate
		{
			get
			{
				return ValidationHelper.GetDateTime(GetValue("EventDate"), DateTimeHelper.ZERO_TIME);
			}
			set
			{
				SetValue("EventDate", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Event fields.
		/// </summary>
		[RegisterProperty]
		public EventFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Event fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class EventFields : AbstractHierarchicalObject<EventFields>
		{
			/// <summary>
			/// The content item of type Event that is a target of the extended API.
			/// </summary>
			private readonly Event mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="EventFields" /> class with the specified content item of type Event.
			/// </summary>
			/// <param name="instance">The content item of type Event that is a target of the extended API.</param>
			public EventFields(Event instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// EventID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.EventID;
				}
				set
				{
					mInstance.EventID = value;
				}
			}


			/// <summary>
			/// EventHeroBannerImage.
			/// </summary>
			public IEnumerable<TreeNode> HeroBannerImage
			{
				get
				{
					return (mInstance.LinkedContentItems["EventHeroBannerImage"]);
				}
			}


			/// <summary>
			/// EventPromoText.
			/// </summary>
			public string PromoText
			{
				get
				{
					return mInstance.EventPromoText;
				}
				set
				{
					mInstance.EventPromoText = value;
				}
			}


			/// <summary>
			/// EventDate.
			/// </summary>
			public DateTime Date
			{
				get
				{
					return mInstance.EventDate;
				}
				set
				{
					mInstance.EventDate = value;
				}
			}


			/// <summary>
			/// EventCafe.
			/// </summary>
			public IEnumerable<TreeNode> Cafe
			{
				get
				{
					return (mInstance.LinkedContentItems["EventCafe"]);
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Event" /> class.
		/// </summary>
		public Event() : base(CLASS_NAME)
		{
			mFields = new EventFields(this);
		}

		#endregion
	}
}